apiVersion: v1
kind: Secret
metadata:
  name: vram-secret
  namespace: vram
type: opaque
data:
  vram-data-admin-password: <base64 password here>
  vram-data-admin-username: bmljd2ViLWFkbWlu
  vram-data-password: <base64 password here>
  vram-data-username: bmljd2ViLXVzZXI=
