# Day Two Operational Guide Implementation

- hosts: all
  become: true
  become_user: root 

  tasks:

  - name: Copy SCC RPM
    ansible.builtin.copy:
      src: ./scc-5.10.1.rhel9.x86_64.rpm
      dest: ~/scc-5.10.1.rhel9.x86_64.rpm
  
  - name: Copy SCC cleanup script
    ansible.builtin.copy:
      src: ./scc_cleanup.sh
      dest: /root/scc_cleanup.sh
      
  - name: Copy SCC k8s Profiles
    ansible.builtin.copy:
      src: ./U_Kubernetes_V2R2_STIG_SCAP_1-3_Benchmark.zip
      dest: /opt/scc/U_Kubernetes_V2R2_STIG_SCAP_1-3_Benchmark.zip

  - name: Copy SCC RHEL Profiles
    ansible.builtin.copy:
      src: ./U_RHEL_9_V2R3_STIG_SCAP_1-3_Benchmark-enhancedV4.zip
      dest: /opt/scc/U_RHEL_9_V2R3_STIG_SCAP_1-3_Benchmark-enhancedV4.zip

  - name: Install SSHPass
    ansible.builtin.dnf:
      name: sshpass
      state: latest

  - name: Import benchmark
    ansible.builtin.shell: |
      dnf remove spawarscc-5.10-0.x86_64 -y
      mkdir -p /opt/scc
      rpm -i ~/scc-5.10.1.rhel9.x86_64.rpm
      /opt/scc/cscc -is /opt/scc/U_RHEL_9_V2R1_STIG_SCAP_1-3_benchmark.zip
      /opt/scc/cscc -is /opt/scc/U_Kubernetes_V2R1_STIG_SCAP_1-3_Benchmark.zip

  - name: Root partition extend
    ansible.builtin.shell: | 
      lvextend -l +100% FREE /dev/mapper/rootvg-rootlv
  
  - name: Finale Reboot
    ansible.builtin.reboot:
      reboot_timeout: 3600

  - name: Install SCAP RPM
    ansible.builtin.shell:
      cmd:  rpm -i ~/scc-5.10_rhel9_x86_64/scc-5.10.rhel9.x86_64.rpm --nodigest

  - name: DNF Updates
    ansible.builtin.shell:
      cmd: dnf update -y

  - name: SCC Cleanup Script Updates
    ansible.builtin.shell:
      cmd: chmod +x /root/scc_cleanup.sh

  - name: SCC Monthly Cleanup Cronjob
    ansible.builtin.cron:
      name: SCAP Cleanup
      minute: "0"
      hour: "20"
      day: "12"
      job: "/root/scc_cleanup.sh"

  - name: SCC Monthly Cronjob
    ansible.builtin.cron:
      name: SCAP Report
      minute: "0"
      hour: "20"
      day: "11"
      job: "/opt/scc/cscc"

    


      

