- hosts: all
  become: true
  become_user: root 

  vars:
    resource_group: <change per environment>


  tasks:

  - name: DNF Updates
    ansible.builtin.shell:
      cmd: dnf update -y
      owner: root
      group: root
      mode: '0644'
    tags:
      - dnf
