
 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
name: pgadmin4-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
storage: 10Gi
 
---
apiVersion: v1
kind: PersistentVolume
metadata:
name: pgadmin4-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /datadrive/pgadmin4

--- 
apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
type: Opaque
data:
  PGADMIN_DEFAULT_EMAIL: <base64 enacode>  #admin@digitaldata.co
  PGADMIN_DEFAULT_PASSWORD: <base64 encode >
 
---
apiVersion: v1
kind: Service
metadata:
name: pgadmin4-service
spec:
  selector:
    app: pgadmin4
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30080
  type: NodePort
 
---
apiVersion: apps/v1
kind: Deployment
metadata:
name: pgadmin4
  labels:
    app: pgadmin4
spec:
  replicas: 1
  selector:
    matchLabels:
app: pgadmin4
  template:
    metadata:
labels:
app: pgadmin4
    spec:
affinity:
nodeAffinity:
requiredDuringSchedulingIgnoredDuringExecution:
nodeSelectorTerms:
- matchExpressions:
- key: kubernetes.io/hostname
operator: In
values:
- scope-tes488dm6
containers:
- name: pgadmin4
image: dpage/pgadmin4:latest
ports:
- containerPort: 80
envFrom:
- secretRef:
name: pgadmin-secret
volumeMounts:
- name: pgadmin-data
mountPath: /var/lib/pgadmin
volumes:
- name: pgadmin-data
persistentVolumeClaim:
claimName: pgadmin4-pvc