---
- hosts: masters
  become: yes
  vars:
   lb_addr: "10.0.0.42"
   master_ip: "10.0.0.41"
  tasks:
    - name: Create the command for joining the other master nodes
      ansible.builtin.shell: 
        kubeadm token create --print-join-command --certificate-key $(kubeadm init phase upload-certs --upload-certs |  awk '{for (i=1;i<3;i++) {getline}; print $0}')
      register: kubernetes_join_command

    - debug: 
        msg: "{{ kubernetes_join_command.stdout }}"

    - name: Copy join command to local file.
      local_action: 
        copy content={{ kubernetes_join_command.stdout }}
        dest="/tmp/test-kubernetes_join_command" 
        mode=0777


# This file is unnecessary, but keeping for Just in Case. This script uses ansible to create the master node join command.