- hosts: all
  become: true
  become_user: root

  tasks:

  - name: Install AIDE package
    ansible.builtin.dnf:
      name: aide
      state: present
    register: aide_result
    ignore_errors: true

  - name: Initialize AIDE
    ansible.builtin.shell: aide --init
    register: aide_init_result
    ignore_errors: true

  - name: Configure boot loader superuser password
    ansible.builtin.shell: |
      echo -e "1qaz2wsx3edc$RFV\n1qaz2wsx3edc$RFV" | grub2-setpassword | awk '/hash of / {print $NF}' >> /boot/grub2/user.cfg
      grub2-mkconfig -o /boot/grub2/grub.cfg
    register: grub_password_result
    ignore_errors: true

  - name: Prevent unrestricted mail relaying
    ansible.builtin.shell: postconf -e 'smtpd_clinet_restrictions = permit_mynetworks,reject'
    register: mail_relay_result
    ignore_errors: true

  - name: Set permissions for cron configuration directories
    ansible.builtin.file:
      path: /etc/cron.d/
      mode: '0700'
      recurse: yes
    register: cron_permissions_result
    ignore_errors: true

  - name: Set permissions for root initialization files
    ansible.builtin.file:
      path: /root
      mode: '0740'
      recurse: yes
    register: root_permissions_result
    ignore_errors: true

  - name: Ensure SSH server configuration file has correct permissions
    ansible.builtin.file:
      path: /etc/ssh/sshd_config.d
      mode: '0600'
      recurse: yes
    register: ssh_permissions_result
    ignore_errors: true

  - name: Ensure account lockouts persist
    ansible.builtin.lineinfile:
      path: /etc/security/faillock.conf
      regexp: '^#?\s*/var/run/faillock'
      line: '/var/log/faillock'
    register: faillock_config_result
    ignore_errors: true

  - name: Restrict ptrace usage
    ansible.builtin.blockinfile:
      path: /etc/sysctl.d/ptrace.conf
      block: |
        kernel.yama.ptrace_scope = 1
    register: ptrace_restrict_result
    ignore_errors: true

  - name: Apply sysctl changes
    ansible.builtin.shell: sysctl --system
    register: sysctl_result
    ignore_errors: true

  - name: Install and enable USBGuard
    ansible.builtin.dnf:
      name: usbguard
      state: present
    register: usbguard_install_result
    ignore_errors: true

  - name: Enable USBGuard logging
    ansible.builtin.lineinfile:
      path: /etc/usbguard/usbguard-daemon.conf
      regexp: '^AuditBackend='
      line: 'AuditBackend=LinuxAudit'
    register: usbguard_logging_result
    ignore_errors: true

  - name: Ensure system clocks are synchronized
    ansible.builtin.lineinfile:
      path: /etc/chrony.conf
      regexp: '^pool 2.rhel.pool.ntp.org iburst maxpoll 16'
      line: 'server 0.us.pool.ntp.mil iburst maxpoll 16'
    register: chrony_config_result
    ignore_errors: true

  - name: Enable pcscd service
    ansible.builtin.systemd:
      name: pcscd
      enabled: yes
      state: started
    register: pcscd_service_result
    ignore_errors: true

  - name: Protect audit logs from unauthorized changes
    ansible.builtin.blockinfile:
      path: /etc/audit/rules.d/audit.rules
      block: |
        --loginuid-immutable
        -e 2
    register: audit_protection_result
    ignore_errors: true

  - name: Enable password protection for sudo commands
    ansible.builtin.shell: find /etc/sudoers /etc/sudoers.d -type f -exec sed -i '/NOPASSWD/ s/^/# /g' {} \;
    register: sudo_protection_result
    ignore_errors: true

  - name: Set password expiration policy
    ansible.builtin.shell: passwd -x 60 -n 1 root
    register: passwd_policy_result
    ignore_errors: true

  - name: Install and configure Postfix
    ansible.builtin.dnf:
      name: postfix
      state: present
    register: postfix_install_result
    ignore_errors: true

  - name: Enable and start Postfix service
    ansible.builtin.systemd:
      name: postfix
      enabled: yes
      state: started
    register: postfix_service_result
    ignore_errors: true

  - name: Update mail aliases
    ansible.builtin.lineinfile:
      path: /etc/aliases
      regexp: '^root:'
      line: 'root: isso'
    register: mail_alias_result
    ignore_errors: true

  - name: Apply changes to mail aliases
    ansible.builtin.shell: newaliases
    register: newaliases_result
    ignore_errors: true

  - name: Fix vm_overcommit_memory issue
    ansible.builtin.shell: sysctl  -w vm/overcommit_memory=1
    register: overcommit_result
    ignore_errors: true

  - name: Fix kernel panic value
    ansible.builtin.shell: sysctl  -w kernel/panic=10
    register: kernel-panic result
    ignore_errors: true
