apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2019-03-12T21:33:47Z"
  generation: 184
  name: vram-ui
  namespace: vram
  resourceVersion: "315519284"
  selfLink: /apis/apps.openshift.io/v1/namespaces/prod/deploymentconfigs/vram-ui
  uid: 8515a8a8-450e-11e9-9d20-0050569b10f1
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: vram-ui
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: vram-ui
    spec:
      containers:
      - image: p314aa02.dc3n.navy.mil:5001/vram/vram-ui:20240916
        imagePullPolicy: Never
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 30
        name: vram-ui
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 1
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 600
        resources:
          limits:
            cpu: "1"
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

