- hosts: all
  become: true
  become_user: root 
  tasks:

  - name: Create SCC directory
    ansible.builtin.shell:
      cmd:  mkdir -p /opt/scc
    tags:
      - dev
      - baseimage
      - dod
      - stig

  - name: Import SCAP RHEL benchmark
    ansible.builtin.shell:
      cmd: /opt/scc/cscc -is /datadrive/airgap/rpms/U_RHEL_9_V2R1_STIG_SCAP_1-3_benchmark.zip
    tags:
      - dev
      - baseimage
      - stig
      - dod
      - redhat

  - name: Import SCAP k8s benchmark
    ansible.builtin.shell:
      cmd: /opt/scc/cscc -is /datadrive/airgap/rpms/U_Kubernetes_V2R1_STIG_SCAP_1-3_Benchmark.zip
    tags:
      - dev
      - baseimage
      - stig
      - dod
      - k8s

  - name: Copy STIG Manual txt file
    ansible.builtin.copy:
      src: ./RHEL_9_STIG_2.1.2_Autoanswer.txt
      dest: /opt/scc/Resources/Content/Manual_Questions/Completed_Files/RHEL_9_STIG_2.1.2_Autoanswer.txt
    tags:
      - dev
      - baseimage
      - redhat
      - dod


  - name: containerd Service
    ansible.builtin.service:
      name: containerd
      enabled: yes
    tags:
      - dev
      - baseimage
      - k8s

  - name: Containerd Setup
    ansible.builtin.shell: | 
      containerd config default | tee /etc/containerd/config.toml
      sed -i 's/3.8/3.9/g' /etc/containerd/config.toml
      sed -i 's/SystemdCgroup = false/SystemdCgroup = true/g' /etc/containerd/config.toml  
      service containerd restart
    tags:
      - dev
      - baseimage
      - k8s

  - name: Modprobe setup
    ansible.builtin.shell:
      cmd:  modprobe overlay
    tags:
      - dev
      - baseimage
      - k8s

  - name: Modprobe setup
    ansible.builtin.shell:
      cmd:  modprobe br_netfilter
    tags:
      - dev
      - baseimage
      - k8s

  - name: IPv4 IP_Forward set perm
    ansible.builtin.shell:
      cmd:  echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
    tags:
      - dev
      - baseimage
      - k8s

  - name: sysctl reload
    ansible.builtin.shell:
      cmd:  sysctl --system
    tags:
      - dev
      - baseimage
      - k8s
        
  - name: Disable SWAP
    ansible.builtin.shell:
      cmd:  swapoff -a
    tags:
      - dev
      - baseimage
      - k8s

  - name: Add user to sudoers
    ansible.builtin.shell:
      cmd: usermod -aG wheel dd
    tags:
      - dev
      - baseimage
      - redhat

  - name: Containerd Service Prep
    ansible.builtin.shell:
       mkdir -p /datadrive/containerd
    tags:
      - dev
      - baseimage
      - k8s

  - name: Run OpenSCAP Evaluation Report and Remediation Creation # Still not as good as running the direct "remediation"
    ansible.builtin.shell: 
      cmd: oscap xccdf generate fix --fix-type bash --fetch-remote-resources --output ~/remediation-script.sh --profile xccdf_org.ssgproject.content_profile_stig --report ~/oscap_report_post.html /usr/share/xml/scap/ssg/content/ssg-rhel9-ds.xml
    tags:
      - dev
      - baseimage
      - redhat
      - stig

  - name: V-258046 - RHEL 9 system accounts must not have an interactive login shell.
    ansible.builtin.shell:
      cmd:  usermod --shell /sbin/nologin "{{ item }}"
    loop:
      - shutdown
      - libstoragemgmt
      - sync
      - sshd
      - setroubleshoot
      - halt
      - clevis 
    tags:
      - dev
      - baseimage
      - stig
      - redhat

  - name: Enable Faillock #V-258055, V-258056, V-258057, V-258060, V-258070
    ansible.builtin.copy:
      src: ./faillock.conf
      dest: /etc/security/faillock.conf
      owner: root
      group: root
      mode: '0644'
    tags:
      - dev
      - baseimage
      - stig
      - redhat

  - name: Execute OpenSCAP Remediation fix # Leaves 9 failures
    ansible.builtin.shell:
      cmd: bash ~/remediation-script.sh
    tags:
      - dev
      - baseimage
      - redhat
      - stig

  - name: Finale Reboot
    ansible.builtin.reboot:
      reboot_timeout: 3600
    tags:
      - dev
      - baseimage



         


