- hosts: all
  become: true
  become_user: root 
  tasks:

  - name: Copy containerd module file with owner and permissions
    ansible.builtin.copy:
      src: ./containerd.conf
      dest: /etc/modules-load.d/containerd.conf
      owner: root
      group: root
      mode: '0644'
    tags:
      - dev
      - baseimage
      - k8s

  - name: Copy POST STIG script
    ansible.builtin.copy:
      src: ./stig_fixes_playbook.sh
      dest: ~/stig_fixes_playbook.sh
      owner: dd
      group: dd
      mode: '0644'
    tags:
      - dev
      - baseimage
      - stig

  - name: Copy STIG Partitions file
    ansible.builtin.copy:
      src: ./stig_partitions.sh
      dest: ~/stig_partitions.sh
    tags:
      - dev
      - baseimage
      - stig

  - name: Copy DATT RPM
    ansible.builtin.copy:
      src: ./CM308935_datt-1.6.26.x86_64.rpm
      dest: ~/CM308935_datt-1.6.26.x86_64.rpm
    tags:
      - dev
      - baseimage
      - DoD

  - name: Enable FIPS
    ansible.builtin.shell:
      cmd:  fips-mode-setup --enable
    tags:
      - dev
      - baseimage
      - stig

  - name: Execute STIG Partitions
    ansible.builtin.shell:
      cmd:  bash ~/stig_partitions.sh
    tags:
      - dev
      - baseimage
      - stig

  - name: Reboot a slow machine that might have lots of updates to apply
    ansible.builtin.reboot:
      reboot_timeout: 3600
    tags:
      - dev
      - baseimage

  - name: Auditd Service Prep
    ansible.builtin.shell: |
      mkdir -p /var/log/audit
      echo "/dev/mapper/rootvg-var--log--audit--lv /var/log/audit   xfs  defaults,nodev,nosuid,noexec        0 0" |  tee -a /etc/fstab
      mount /dev/mapper/rootvg-var--log--audit--lv /var/log/audit
    tags:
      - dev
      - baseimage
      - stig

  - name: Resetup audit service
    ansible.builtin.shell: |
       chmod 700 /var/log/audit
       chcon -t auditd_log_t /var/log/audit
    tags:
      - dev
      - baseimage
      - stig

  - name: Enable and Start auditd service
    ansible.builtin.shell:
      service auditd restart
    tags:
      - dev
      - baseimage
      - stig

  - name: Register system with Red Hat #To be updated to DoD Satellite Server
    ansible.builtin.shell:  subscription-manager register --username cdixon@digitaldata.co --password zsA6ys*GVhQyKHxS4kB@weNAJmM@Z8yENasxoGruXK#^E#bmN^#tJY^J%FATQHa --auto-attach --force
    tags:
      - dev
      - baseimage
      - redhat

  - name: Add Kubernetes Repo
    yum_repository:
     name: Kubernetes
     description: Kubernetes
     baseurl: https://pkgs.k8s.io/core:/stable:/v1.30/rpm
     enabled: yes
     gpgcheck: yes
     gpgkey: https://pkgs.k8s.io/core:/stable:/v1.30/rpm/repodata/repomd.xml.key
    tags:
      - dev
      - baseimage
      - k8s

  - name: Add Docker Repo
    ansible.builtin.shell:
      cmd:  dnf config-manager --add-repo=https://download.docker.com/linux/rhel/docker-ce.repo
    tags:
      - dev
      - baseimage
      - k8s

  - name: Red Hat set Release Version
    ansible.builtin.shell:
      cmd:  subscription-manager release --set=9.4
    tags:
      - dev
      - baseimage
      - redhat

  - name: Repo Refresh 
    ansible.builtin.shell:
      cmd:  dnf upgrade --refresh -y
    tags:
      - dev
      - baseimage
      - redhat

  - name: Ensure system is up to date
    dnf:
      update_cache: true
      name: "*"
      state: latest
    tags:
      - dev
      - baseimage
      - redhat

  - name: Copy Air Gap directory and contents to Base Image
    ansible.builtin.copy:
      src: ./airgap
      dest: /datadrive/
      owner: root
      group: root
      mode: '0644'
    tags:
      - dev
      - baseimage
      - k8s

  - name: AirGap RPM install
    ansible.builtin.shell:
      cmd: dnf install -y /datadrive/airgap/rpms/*
    tags:
      - dev
      - baseimage
      - redhat

  - name: Create SCC directory
    ansible.builtin.shell:
      cmd:  mkdir -p /opt/scc
    tags:
      - dev
      - baseimage
      - dod
      - stig

  - name: Import SCAP RHEL benchmark
    ansible.builtin.shell:
      cmd: /opt/scc/cscc -is /datadrive/airgap/rpms/U_RHEL_9_V2R1_STIG_SCAP_1-3_benchmark.zip
    tags:
      - dev
      - baseimage
      - stig
      - dod
      - redhat

  - name: Import SCAP k8s benchmark
    ansible.builtin.shell:
      cmd: /opt/scc/cscc -is /datadrive/airgap/rpms/U_Kubernetes_V2R1_STIG_SCAP_1-3_Benchmark.zip
    tags:
      - dev
      - baseimage
      - stig
      - dod
      - k8s

  - name: Copy STIG Manual txt file
    ansible.builtin.copy:
      src: ./RHEL_9_STIG_2.1.2_Autoanswer.txt
      dest: /opt/scc/Resources/Content/Manual_Questions/Completed_Files/RHEL_9_STIG_2.1.2_Autoanswer.txt
    tags:
      - dev
      - baseimage
      - redhat
      - dod


  - name: containerd Service
    ansible.builtin.service:
      name: containerd
      enabled: yes
    tags:
      - dev
      - baseimage
      - k8s

  - name: Containerd Setup #sed -i 's/3.8/3.9/g' /etc/containerd/config.toml #nolongernecessary
    ansible.builtin.shell: | 
      containerd config default | tee /etc/containerd/config.toml
      sed -i 's/SystemdCgroup = false/SystemdCgroup = true/g' /etc/containerd/config.toml  
      service containerd restart
    tags:
      - dev
      - baseimage
      - k8s

  - name: Modprobe setup
    ansible.builtin.shell:
      cmd:  modprobe overlay
    tags:
      - dev
      - baseimage
      - k8s

  - name: Modprobe setup
    ansible.builtin.shell:
      cmd:  modprobe br_netfilter
    tags:
      - dev
      - baseimage
      - k8s

  - name: IPv4 IP_Forward set perm
    ansible.builtin.shell:
      cmd:  echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
    tags:
      - dev
      - baseimage
      - k8s

  - name: sysctl reload
    ansible.builtin.shell:
      cmd:  sysctl --system
    tags:
      - dev
      - baseimage
      - k8s
        
  - name: Disable SWAP
    ansible.builtin.shell:
      cmd:  swapoff -a
    tags:
      - dev
      - baseimage
      - k8s

  - name: Add user to sudoers
    ansible.builtin.shell:
      cmd: usermod -aG wheel dd
    tags:
      - dev
      - baseimage
      - redhat

  - name: Containerd Service Prep
    ansible.builtin.shell:
       mkdir -p /datadrive/containerd
    tags:
      - dev
      - baseimage
      - k8s

  - name: Run OpenSCAP Evaluation Report and Remediation Creation # Still not as good as running the direct "remediation"
    ansible.builtin.shell: 
      cmd: oscap xccdf generate fix --fix-type bash --fetch-remote-resources --output ~/remediation-script.sh --profile xccdf_org.ssgproject.content_profile_stig --report ~/oscap_report_post.html /usr/share/xml/scap/ssg/content/ssg-rhel9-ds.xml
    tags:
      - dev
      - baseimage
      - redhat
      - stig

  - name: V-258046 - RHEL 9 system accounts must not have an interactive login shell.
    ansible.builtin.shell:
      cmd:  usermod --shell /sbin/nologin "{{ item }}"
    loop:
      - shutdown
      - libstoragemgmt
      - sync
      - sshd
      - setroubleshoot
      - halt
      - clevis 
    tags:
      - dev
      - baseimage
      - stig
      - redhat

  - name: Enable Faillock #V-258055, V-258056, V-258057, V-258060, V-258070
    ansible.builtin.copy:
      src: ./faillock.conf
      dest: /etc/security/faillock.conf
      owner: root
      group: root
      mode: '0644'
    tags:
      - dev
      - baseimage
      - stig
      - redhat

  - name: Execute STIG Fixes script
    ansible.builtin.shell:
      cmd: bash ~/./stig_fixes_playbook.sh
    tags:
      - dev
      - baseimage
      - redhat
      - stig

  - name: Execute OpenSCAP Remediation fix # Leaves 9 failures
    ansible.builtin.shell:
      cmd: bash ~/remediation-script.sh
    tags:
      - dev
      - baseimage
      - redhat
      - stig

  - name: Finale Reboot
    ansible.builtin.reboot:
      reboot_timeout: 3600
    tags:
      - dev
      - baseimage



         

