name: Build Multi-Architecture Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v4

    # Create a new builder instance
    - name: Create Buildx builder
      run: docker buildx create --use

    # Inspect the Buildx builder (optional for debugging)
    - name: Inspect Buildx builder
      run: docker buildx inspect --bootstrap

    # Build and save the image for amd64 from the 'image' subdirectory
    - name: Build Docker image for amd64
      run: |
        docker buildx build --platform linux/amd64 --output type=docker,dest=product.oci.amd64 ./image

    # Optionally upload both OCI archives as artifacts
    - name: Upload amd64 OCI archive
      uses: actions/upload-artifact@v4
      with:
        name: product.oci.amd64
        path: product.oci.amd64
